version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.16-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run: npm install
      - run: npm test
